### ISSUE TITLE
UnsplashUsers::statistics has a typo

### ISSUE THREAD

**Issue by Katalam** [shweshi/Laravel-Unsplash-Wrapper#13]
As is the readme mentioned

```php
$statistics   = UnsplashUsers::statistics($username, $params);   // single user's statistics
```
but it is acutally called statics as shown here
https://github.com/shweshi/Laravel-Unsplash-Wrapper/blob/12b728f0b91a2603597f04342131c9cecac9c2fc/src/UnsplashUsers.php#L80-L83

**Comment by shweshi** [comment]
@Katalam thanks for pointing it out. Will it possible for you to open a PR to fix this. Let me know if you want to take this up.

**Comment by Katalam** [comment]
#14

**Comment by shweshi** [comment]
Thanks @Katalam
